### ISSUE TITLE
Hyperlink Linter Improvements Tracker

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/docs#94]
### Purpose

Track all issues related to improving the hyperlink linter in one place

### To Do
- [x] #88 
- [ ] https://github.com/UBCSailbot/docs/issues/107
- [ ] External link to site used instead of internal link; for example if we are in `docs/`:
    ```
    [homepage](https://ubcsailbot.github.io/docs/index.md) -> [homepage](./index.md)
    ``` 
- [ ] Internal link opens in new tab instead of in the same tab
    ```
   [homepage](./index.md){target=_blank} -> [homepage](./index.md)
    ``` 
    - This could be configurable
- [ ] Publish in its own repo
- [ ] Support new format: https://github.com/UBCSailbot/docs/pull/129#discussion_r1117907046
- [ ] No bare URLs

### Notes
- If you want to test the linter locally, copy the [`lint_links.py`](https://github.com/UBCSailbot/docs/tree/main/.github/actions/lint) file to the root directory of the project and run it there. Remember to not commit the file in the root directory and put all your final changes in the file in the actions folder!
- You will need to be familiar with regular expressions to develop this linter. Refer to the resources below.
- You will be interested in the follow for these issues:
  - [These files](https://github.com/UBCSailbot/docs/tree/main/.github/actions/lint)
  - The following lines in [lint.yml](https://github.com/UBCSailbot/docs/blob/main/.github/workflows/lint.yml):
https://github.com/UBCSailbot/docs/blob/ce44c5787b7c1571eac5ee3332eb67e81b7f69a1/.github/workflows/lint.yml#L38-L52

### Resources

- https://github.com/UBCSailbot/docs/pull/86
- [Learn Regex](https://regexone.com/)
- [Test Regex](https://regex101.com/) -- Use the "Python" flavor and not the default PHP flavor.
- [Understand GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions)
